apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-generator
  labels:
    app: id-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id-generator
  template:
    metadata:
      labels:
        app: id-generator
    spec:
      containers:
        - name: id-generator
          image: id-generator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: id-generator
spec:
  selector:
    app: id-generator
  ports:
    - port: 8080
      targetPort: 8080
